### ISSUE TITLE
Building of docs failed

### ISSUE THREAD

**Issue by jakubjedelsky** [ultrabug/py3status#1012]
Hi,

I'm preparing rpm for Fedora with 3.6 version and just realized, that I'm not able to build docs. The error is the same for `make html` within `doc` dir and for `sphinx-build-3 -d doctree doc html` (the `-3` means it uses python3 version of sphinx) command.

```
Exception occurred:
  File "conf.py", line 5, in <module>
    from py3status.autodoc import (
ImportError: cannot import name 'ScreenshotDirective'

# Full stack of sphinx
# Sphinx version: 1.6.3
# Python version: 3.6.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python3.6/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 5, in <module>
    from py3status.autodoc import (
ImportError: cannot import name 'ScreenshotDirective'
```

I checked that the class is there and I'm not able to find a problem. Is there something I missed? Can you help, please?

Thanks,
jj

**Comment by tobes** [comment]
maybe it is a problem with the sphinx or python version.  It all works for me however

```
$ sphinx-build-3 --version
Sphinx (sphinx-build) 1.5.2

$ python3 --version
Python 3.5.3
```
pip thinks I have the python modules the same as you do.

I'll upgrade to F26 I'm still on F25 so I'll see if that helps recreate this

can you import it normally?
```
$ python3
Python 3.5.3 (default, May 10 2017, 15:05:55) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from py3status.autodoc import (
...     create_auto_documentation,
...     Py3statusLexer,
...     ScreenshotDirective
... )
>>> ScreenshotDirective
<class 'py3status.autodoc.ScreenshotDirective'>
>>> 
```

**Comment by tobes** [comment]
if you apply this patch - it removes this feature (currently not used)

do the docs then build?

```diff
diff --git a/doc/conf.py b/doc/conf.py
index b4b6e3a..d206b02 100644
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -5,7 +5,6 @@ import re
 from py3status.autodoc import (
     create_auto_documentation,
     Py3statusLexer,
-    ScreenshotDirective
 )
 from py3status.version import version as py3_version
 
@@ -180,6 +179,3 @@ def setup(sphinx):
     # add the py3status lexer (for code blocks)
     from sphinx.highlighting import lexers
     lexers['py3status'] = Py3statusLexer()
-
-    # enable screenshot directive for dynamic screenshots
-    sphinx.add_directive('screenshot', ScreenshotDirective)
diff --git a/py3status/autodoc.py b/py3status/autodoc.py
index fd46503..0556e8c 100644
--- a/py3status/autodoc.py
+++ b/py3status/autodoc.py
@@ -6,7 +6,6 @@ import os.path
 import re
 
 from docutils import nodes
-from docutils.parsers.rst import Directive
 from pygments.lexer import RegexLexer
 import pygments.token as pygments_token
 
@@ -289,39 +288,5 @@ def create_auto_documentation():
     create_py3_docs()
 
 
-class ScreenshotDirective(Directive):
-    """
-    Adds the ability to add screenshots dynamically in sphinx documentation
-
-    .. screenshot::
-
-        {'color': '#00FF00', 'full_text': 'Example output'}
-
-    """
-
-    has_content = True
-
-    def run(self):
-        env = self.state.document.settings.env
-
-        targetid = "screenshot-%d" % env.new_serialno('screenshot')
-        targetnode = nodes.target('', '', ids=[targetid])
-
-        image_name = '_%s' % targetid
-        try:
-            content = ast.literal_eval('\n'.join(self.content))
-        except:
-            content = {
-                'color': '#990000',
-                'background': '#FFFF00',
-                'full_text': ' IMAGE DATA ERROR ',
-            }
-
-        process(image_name, content, False)
-        image_path = os.path.join('screenshots', image_name + '.png')
-        screenshot_node = nodes.image(uri=image_path)
-        return [targetnode, screenshot_node]
-
-
 if __name__ == '__main__':
     create_auto_documentation()
```

I'll look into this some more once I'm on F26 (tomorrow)

**Comment by tobes** [comment]
Ok, so building `make html`on F26 worked for me.

`sphinx-build-3 -d doctree doc html` failed due to a hard coded path, which can be easily fixed.

`sphinx-build-3 -d doctree . html` in the doc dir works fine

maybe check you have run `setup.py` in case you have a stale version somewhere

**Comment by jakubjedelsky** [comment]
@tobes many thanks for your help, it was just my error. I didn't realized, that sphinx is taking py3status module installed on my system during testing 🤦‍ During building rpm, I have to edit PYTHONPATH variable to dir with module and it's ok then.

Thanks and sorry again.
