### ISSUE TITLE
python 3.5 broke py3status on arch linux

### ISSUE THREAD

**Issue by ndalliard** [ultrabug/py3status#122]
I updated to python 3.5 yesterday on my arch linux machine and that broke py3status.

Here the error message I get:

````
Traceback (most recent call last):
  File "/usr/bin/py3status", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'py3status==2.6' distribution was not found and is required by the application
````

**Comment by ultrabug** [comment]
Hi Nate,

I think this is normal since py3status is seen as a python package. Did you install it using AUR or pip ?

If you did use pip, you have to reinstall it manually since pip has no python version dependency tracking (the same will happen with all your manually installed pip packages)

If you did use AUR, then I guess there is a missing python version dependency tracking as pacman should have triggered a rebuild of all your python packages.

**Comment by ndalliard** [comment]
I did it with the AUR. How can I manually trigger a rebuild of all my python packages? Thanks!

**Comment by ultrabug** [comment]
ping @Horgix for information, maybe something is missing to tell the AUR package to automatically rebuild when a new python version is released.
