### ISSUE TITLE
Problem setting locale

### ISSUE THREAD

**Issue by suuuehgi** [ultrabug/py3status#1877]
On the current Arch version 
```
py3status version 3.22 (python 3.8.0) on i3
```

line 37 of `__init__.py` seems to break py3status for me:

```python
    try:
        locale.setlocale(locale.LC_ALL, "")
    except locale.Error:
        print("No locale available")
        sys.exit(2)
```
**MWE**
```python
Python 3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, "")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
I manually changed it to `locale.setlocale(locale.LC_ALL)` for now to get it going again.

**Comment by ultrabug** [comment]
Hi @suuuehgi 

How is your machine's locale configured please? Could you share the following:

- result of `locale` command
- content of `/etc/locale.gen`
- content of `/etc/locale.conf`

Also, just to know if you have python3.7 installed, could you check using that version or another one?

Thanks!

**Comment by suuuehgi** [comment]
After a reboot, it works again. :S 
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

```
de_DE.UTF-8 UTF-8  
en_US.UTF-8 UTF-8
```

```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_ALL=C
```
