### ISSUE TITLE
Path in args are no longer correctly parsed

### ISSUE THREAD

**Issue by X-dark** [ultrabug/py3status#1986]
It seems there is still issues following https://github.com/ultrabug/py3status/pull/1978

When I launch py3status without args, it gets my config file in one of the default locations and works fine. But it crashes if I try to set a config argument. I tried to set log file location to debug but it crashes as well.

The error with the log file is the following (I cannot see the error for the config file but I suspect it to be similar):

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/py3status/__init__.py", line 38, in main
    py3.setup()
  File "/usr/lib/python3.9/site-packages/py3status/core.py", line 538, in setup
    self.log("=" * 8)
  File "/usr/lib/python3.9/site-packages/py3status/core.py", line 866, in log
    with self.config["log_file"].open("ab") as f:
AttributeError: 'str' object has no attribute 'open'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/py3status", line 13, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/py3status/__init__.py", line 45, in main
    py3.report_exception("Setup error")
  File "/usr/lib/python3.9/site-packages/py3status/core.py", line 230, in report_exception
    self.py3_wrapper.log(msg, "warning")
  File "/usr/lib/python3.9/site-packages/py3status/core.py", line 866, in log
    with self.config["log_file"].open("ab") as f:
AttributeError: 'str' object has no attribute 'open'
```

**Comment by ultrabug** [comment]
Thanks @X-dark ! I've fixed all of those
