### ISSUE TITLE
Error: status_command process exited unexpectedly (exit 1)

### ISSUE THREAD

**Issue by xpecel** [ultrabug/py3status#2164]
The error occurred after I finished updating my system. 

This is the error message I get in version 3.47_2:
```
[libi3] ../i3bar/src/main.c i3bar version 4.21.1 (2022-10-28)
[libi3] ../libi3/font.c Using Pango font JetBrains Mono, size 12
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (py3status 3.47 (/usr/lib/python3.11/site-packages), Requirement.parse('py3status==3.45'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/fann/.local/bin/py3status", line 13, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/py3status/__init__.py", line 27, in main
    from py3status.core import Py3statusWrapper
  File "/usr/lib/python3.11/site-packages/py3status/core.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'py3status==3.45' distribution was not found and is required by the application
[../i3bar/src/child.c:384] ERROR: stdin: received EOF
[../i3bar/src/child.c:506] ERROR: Child (pid: 23350) unexpectedly exited with status 1
```

After that I tried to downgrade to version 3.45_1. This is the error message I got:

``` 
pkill i3bar; i3bar --bar_id=bar-0
[libi3] ../i3bar/src/main.c i3bar version 4.21.1 (2022-10-28)
[libi3] ../libi3/font.c Using Pango font JetBrains Mono, size 12
Traceback (most recent call last):
  File "/usr/bin/py3status", line 9, in <module>
    from py3status import main
ImportError: cannot import name 'main' from 'py3status' (unknown location)
[../i3bar/src/child.c:384] ERROR: stdin: received EOF
[../i3bar/src/child.c:506] ERROR: Child (pid: 9840) unexpectedly exited with status 1
```

I've also tried running it without using a single module but still get the same error.

**Comment by lasers** [comment]
I think this have nothing to do with py3status. How is py3status installed and what distro? I think you need to look at how py3status was installed... It may have to do more with your python, pip, or something else. Sorry if this is not helpful. https://stackoverflow.com/questions/55657036/importerror-cannot-import-name-app-from-mypackage-unknown-location

**Comment by xpecel** [comment]
I use Void linux and installed it with xbps.

**Comment by xpecel** [comment]
I don't understand. After I uninstalled py3status and reinstalled, it worked again. So, I guess it's solved now. lol.
