### ISSUE TITLE
List index ot f range with module tztime

### ISSUE THREAD

**Issue by piquev** [ultrabug/py3status#362]
since the v3, I have an error when i add the module tztime

"py3status: list index out of range please try to fix this and reload i3wm" 

> My i3satus.conf

```
order += "tztime local"

tztime local{
        format = "%Y-%m-%d %H:%M:%S"
}
```

thx for any help

**Comment by tobes** [comment]
Hi,

Is that your entire config?  For me using 3.0/master this works as expected.  Do you still have the issue if you run with that as the full config?

**Comment by piquev** [comment]
it's not my full config file,
but when i comment every thing except this i have this error ...

there is my full config file

```
# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

# ß
general {
        colors = true
        interval = 5
        output_format = i3bar
        color_good = "#2267a5"
       color_degraded = "#8c7f22"
       color_bad = "#be2422"
}

order += "netdata"
order += "whatismyip"
order += "xrandr"
order += "disk /"
order += "battery 0"
order += "whoami"
order += "tztime local"

netdata {
  nic = "wlp58s0"
}

disk "/" {
       format = " Disk: %free "
}

battery 0 {
       format = "%status %percentage %remaining "
       path = "/sys/class/power_supply/BAT0/uevent"
       low_threshold = 20
}

tztime local{
        format = "%Y-%m-%d %H:%M:%S"
}

```

**Comment by tobes** [comment]
I can't replicate this here.  Is there anything in the logs?

running something like ` py3status -c ~/.i3/test.conf -l /tmp/py3status.log` should hopefully give some info.

**Comment by piquev** [comment]
```
2016-07-11 16:26:54 WARNING Setup error (IOError) i3status.py line 282.
2016-07-11 16:26:54 INFO Traceback
IOError: [Errno 2] No such file or directory: '/home/vpi//.i3/test.conf'
  File "/usr/lib64/python2.7/site-packages/py3status/__init__.py", line 17, in main
    py3.setup()
  File "/usr/lib64/python2.7/site-packages/py3status/core.py", line 281, in setup
    self.i3status_thread = I3status(self)
  File "/usr/lib64/python2.7/site-packages/py3status/i3status.py", line 175, in __init__
    self.config = self.i3status_config_reader(config_path)
  File "/usr/lib64/python2.7/site-packages/py3status/i3status.py", line 282, in i3status_config_reader
    for line in open(i3status_config_path, 'r'):

2016-07-11 16:26:54 ERROR py3status: Setup error (IOError) i3status.py line 282. Please try to fix this and reload i3wm (Mod+Shift+R)
2016-07-11 16:28:15 INFO i3status spawned using config file /tmp/py3status_1pysdC
2016-07-11 16:28:15 ERROR list index out of range
2016-07-11 16:28:15 ERROR py3status: list index out of range Please try to fix this and reload i3wm (Mod+Shift+R)
2016-07-11 16:28:15 INFO loading module "netdata" from py3status.modules.netdata
2016-07-11 16:28:15 INFO loading module "whatismyip" from py3status.modules.whatismyip
2016-07-11 16:28:15 INFO loading module "xrandr" from py3status.modules.xrandr
2016-07-11 16:28:15 INFO loading module "whoami" from py3status.modules.whoami
2016-07-11 16:29:19 INFO i3status spawned using config file /tmp/py3status_017dv8
2016-07-11 16:29:19 ERROR list index out of range
2016-07-11 16:29:19 ERROR py3status: list index out of range Please try to fix this and reload i3wm (Mod+Shift+R)
2016-07-11 16:29:19 INFO loading module "netdata" from py3status.modules.netdata
2016-07-11 16:29:19 INFO loading module "whatismyip" from py3status.modules.whatismyip
2016-07-11 16:29:19 INFO loading module "xrandr" from py3status.modules.xrandr
2016-07-11 16:29:19 INFO loading module "whoami" from py3status.modules.whoami
```

The strange things is that my i3status bar work but i don t have the battery,disk modules
(i don't get the error with the file, since he exist and got user rights)

**Comment by tobes** [comment]
> The strange things is that my i3status bar work but i don t have the battery,disk modules

This is because i3status has crashed.

There should be a config for it in `/tmp/py3status_017dv8` or a similarly named file.  Could you paste that here.

**Comment by piquev** [comment]
nop i don t have this file, looks like he is generated with my i3status.conf and removed just after

**Comment by tobes** [comment]
there should be a `/tmp/py3status_xxx` when py3status is running

**Comment by piquev** [comment]
no, i really don t have this file, and i have no idea why : / every time i launch the command, there is no files created in /tmp

**Comment by tobes** [comment]
>The strange things is that my i3status bar work but i don t have the battery,disk modules

Do these modules show when you don't include `tztime local`?

**Comment by pydsigner** [comment]
> `tztime local{`

What happens if you change this to `tztime local {` (adding a space between `local` and the open brace)?

**Comment by tobes** [comment]
If you save this as `test.conf` and then run `i3status -c test.conf` what is the output?
```
order += "disk /"
order += "battery 0"
order += "tztime local"

general {
    output_format = "i3bar"
    color_degraded = "#8c7f22"
    colors = "true"
    color_good = "#2267a5"
    color_bad = "#be2422"
    color_separator = "#333333"
    interval = "5"
}

disk / {
    format = " Disk: %free "
}

battery 0 {
    path = "/sys/class/power_supply/BAT0/uevent"
    format = "%status %percentage %remaining "
    low_threshold = "20"
}

tztime local {
    format = "%Y-%m-%d %H:%M:%S %Z"
}
```

What version of i3status do you have?
`i3status -v`  and which distro are you using?

**Comment by piquev** [comment]
Output

```
py3status -c ~/.i3/test.conf
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/site-packages/py3status/i3status.py", line 529, in run
    self.spawn_i3status()
  File "/usr/lib64/python2.7/site-packages/py3status/i3status.py", line 591, in spawn_i3status
    self.py3_wrapper.log(err, 'error')
  File "/usr/lib64/python2.7/site-packages/py3status/core.py", line 459, in log
    syslog(level, msg)
TypeError: [priority,] message string

{"click_events": true, "stop_signal": 20, "version": 1}
[[]
,[{"name": "net_speed", "full_text": ""}, {"name": "net_traffic", "full_text": ""},{"name": "whatismyip", "full_text": ""},{"name": "xrandr", "full_text": ""},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468321270.654666},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:10"}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 77170.1\u2193 8821.1\u2191", "cached_until": 1468319472.655621}, {"name": "net_traffic", "full_text": ""},{"name": "whatismyip", "full_text": ""},{"name": "xrandr", "full_text": ""},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468321270.654666},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:10"}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 77170.1\u2193 8821.1\u2191", "cached_until": 1468319472.655621}, {"name": "net_traffic", "full_text": ""},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468319500.766018},{"name": "xrandr", "full_text": ""},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468321270.654666},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:10"}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 77170.1\u2193 8821.1\u2191", "cached_until": 1468319472.655621}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):  75\u2193   9\u2191  84\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468319500.766018},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468319481.004336},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468321270.654666},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:11"}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 77170.1\u2193 8821.1\u2191", "cached_until": 1468319472.655621}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):  75\u2193   9\u2191  84\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468319500.766018},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468319481.004336},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468321270.654666},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:12"}]
,[{"color": "#be2422", "instance": "", "name": "netdata", "full_text": "LAN(Kb):   6.4\u2193   1.7\u2191", "cached_until": 1468319474.658692}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):  75\u2193   9\u2191  84\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468319500.766018},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468319481.004336},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468321270.654666},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:12"}]
,[{"color": "#be2422", "instance": "", "name": "netdata", "full_text": "LAN(Kb):   6.4\u2193   1.7\u2191", "cached_until": 1468319474.658692}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):  75\u2193   9\u2191  84\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468319500.766018},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468319481.004336},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468321270.654666},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:13"}]
,[{"color": "#be2422", "instance": "", "name": "netdata", "full_text": "LAN(Kb):   6.4\u2193   1.7\u2191", "cached_until": 1468319474.658692}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):  75\u2193   9\u2191  84\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468319500.766018},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468319481.004336},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468321270.654666},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:14"}]
```

Version 

`i3status 2.7 (2013-02-27) © 2008-2012 Michael Stapelberg and contributors`

I'm using gentoo 4.4.6

**Comment by tobes** [comment]
__i3status__ -c test.conf

**Comment by piquev** [comment]
oups sry, i commanted netdata because it was outputting an error

```
i3status -c ~/.i3/test.conf
{"version":1}
[
[{"name":"disk_info","instance":"/","full_text":" Disk: 436.1 GB "},{"name":"battery","instance":"/sys/class/power_supply/BAT0/uevent","full_text":"FULL 100.00% 00:00:00 "},{"name":"tztime","full_text":"2016-07-12 10:39:30"}]
,[{"name":"disk_info","instance":"/","full_text":" Disk: 436.1 GB "},{"name":"battery","instance":"/sys/class/power_supply/BAT0/uevent","full_text":"FULL 100.00% 00:00:00 "},{"name":"tztime","full_text":"2016-07-12 10:39:35"}]
,[{"name":"disk_info","instance":"/","full_text":" Disk: 436.1 GB "},{"name":"battery","instance":"/sys/class/power_supply/BAT0/uevent","full_text":"FULL 100.00% 00:00:00 "},{"name":"tztime","full_text":"2016-07-12 10:39:40"}]
```

**Comment by tobes** [comment]
saying that you have this in your py3status output so you should be seeing the time
`{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:31:11"}`

can you confirm that in your test config the part for tztime is as follows
```
tztime local {
    format = "%Y-%m-%d %H:%M:%S %Z"
}
```
especially the __%Z__

**Comment by piquev** [comment]
Nop i had not the %Z just added it still got the same error and the %Z value returned is empty

```
{"click_events": true, "stop_signal": 20, "version": 1}
[[]
,[{"name": "net_speed", "full_text": ""}, {"name": "net_traffic", "full_text": ""},{"name": "whatismyip", "full_text": ""},{"name": "xrandr", "full_text": ""},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468322977.265348}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 8554.6\u2193 1486.4\u2191", "cached_until": 1468321179.267294}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):   8\u2193   1\u2191  10\u2195"},{"name": "whatismyip", "full_text": ""},{"name": "xrandr", "full_text": ""},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468322977.265348}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 8554.6\u2193 1486.4\u2191", "cached_until": 1468321179.267294}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):   8\u2193   1\u2191  10\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468321207.369765},{"name": "xrandr", "full_text": ""},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468322977.265348}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 8554.6\u2193 1486.4\u2191", "cached_until": 1468321179.267294}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):   8\u2193   1\u2191  10\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468321207.369765},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468321187.68326},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468322977.265348}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 8554.6\u2193 1486.4\u2191", "cached_until": 1468321179.267294}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):   8\u2193   1\u2191  10\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468321207.369765},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468321187.68326},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468322977.265348},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:59:38 "}]
,[{"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "LAN(Kb): 8554.6\u2193 1486.4\u2191", "cached_until": 1468321179.267294}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):   8\u2193   1\u2191  10\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468321207.369765},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468321187.68326},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468322977.265348},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:59:39 "}]
,[{"color": "#be2422", "instance": "", "name": "netdata", "full_text": "LAN(Kb):   4.4\u2193   1.9\u2191", "cached_until": 1468321181.270491}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):   8\u2193   1\u2191  10\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468321207.369765},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468321187.68326},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468322977.265348},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:59:39 "}]
,[{"color": "#be2422", "instance": "", "name": "netdata", "full_text": "LAN(Kb):   4.4\u2193   1.9\u2191", "cached_until": 1468321181.270491}, {"color": "#2267a5", "instance": "", "name": "netdata", "full_text": "T(Mb):   8\u2193   1\u2191  10\u2195"},{"instance": "", "name": "whatismyip", "full_text": "172.17.15.15, unknown, 195.66.82.9", "cached_until": 1468321207.369765},{"color": "#2267a5", "instance": "", "name": "xrandr", "full_text": "  DP1   ", "cached_until": 1468321187.68326},{"instance": "", "name": "whoami", "full_text": "vpi", "cached_until": 1468322977.265348},{"instance": "local", "name": "tztime", "full_text": "2016-07-12 10:59:40 "}]


```

**Comment by tobes** [comment]
I'm interested in the i3status output not the py3status with that config

**Comment by piquev** [comment]
empty too 

`{"version":1}
[
[{"name":"disk_info","instance":"/","full_text":" Disk: 436.1 GB "},{"name":"battery","instance":"/sys/class/power_supply/BAT0/uevent","full_text":"FULL 100.00% 00:00:00 "},{"name":"tztime","full_text":"2016-07-12 11:06:00 "}]
,[{"name":"disk_info","instance":"/","full_text":" Disk: 436.1 GB "},{"name":"battery","instance":"/sys/class/power_supply/BAT0/uevent","full_text":"FULL 100.00% 00:00:00 "},{"name":"tztime","full_text":"2016-07-12 11:06:05 "}]
`

**Comment by tobes** [comment]
OK,

So the problem is that `%Z` is not being interpreted by i3status.  This then cause `I3statusModule.set_time_zone()` to fail.  This then stops other i3StatusModules from doing an update (although the tztime does update).

So this probably needs a fix for when this happens.  I'm not sure why %Z is not supported is it available in `man strftime`?

The other option is that it is something to do with i3status 2.7 the current version is 2.10 I suspect that might be the cause

**Comment by piquev** [comment]
Yeah it was that thx for your help
my Timezone wasn t set : /
Sry to have lose your time

Everything is working now
