### ISSUE TITLE
group module cannot be loaded

### ISSUE THREAD

**Issue by ikzk** [ultrabug/py3status#387]
I am using the master branch. I simply put the example in the doc:

```
# Create a disks group that will show space on '/' and '/home'
# Change between disk modules every 30 seconds
...
order += "group disks"
...

group disks {
    cycle = 30
    format = "Disks: {output} {button}"
    click_mode = "button"

    disk "/" {
        format = "/ %avail"
    }

    disk "/home" {
        format = "/home %avail"
    }
}
```

to my configuration file (I also tried an empty configuration file). An error is reported:

```
py3status: Setup error (RuntimeError) parse_config.py line 544. Please try to fix this and reload i3wm (Mod+Shift+R)
```

Without group module or when the group module only contains a single module it works fine.

**Comment by ultrabug** [comment]
Hi @ikzk, that's strange, would you mind showing the result of `py3status -v` and if possible your entire `i3status.conf` when it's failing ?

**Comment by tobes** [comment]
Could you also post the error from the logs.  `py3status -c <config-path> -l <logfile-path>` Thanks

**Comment by ikzk** [comment]
@ultrabug @tobes Sorry for replying late. 

The `py3status -v` shows:

```
py3status version 3.1rc0 (python 3.5.2)
```

The `i3status.conf` is

```
general {
        colors = true
        interval = 5
}

order += "group disks"

group disks {
    cycle = 30
    format = "Disks: {output} {button}"
    click_mode = "button"

    disk "/" {
        format = "/ %avail"
    }

    disk "/home" {
        format = "/home %avail"
    }
}
```

The error log is

```
2016-08-04 14:26:26 WARNING Setup error (RuntimeError) parse_config.py line 544.
2016-08-04 14:26:26 INFO Traceback
RuntimeError: OrderedDict mutated during iteration
  File "/home/alice/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/py3status/__init__.py", line 23, in main
    py3.setup()
  File "/home/alice/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/py3status/core.py", line 276, in setup
    config = process_config(config_path, self)
  File "/home/alice/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/py3status/parse_config.py", line 562, in process_config
    get_modules(config_info)
  File "/home/alice/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/py3status/parse_config.py", line 558, in get_modules
    module = process_module(k, v, parent)
  File "/home/alice/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/py3status/parse_config.py", line 544, in process_module
    for k, v in module.items():

2016-08-04 14:26:26 ERROR py3status: Setup error (RuntimeError) parse_config.py line 544. Please try to fix this and reload i3wm (Mod+Shift+R)
```

**Comment by ikzk** [comment]
I also tried using system's python instead of the anaconda virtualenv, but the error persists:

```
2016-08-04 14:29:01 WARNING Setup error (RuntimeError) parse_config.py line 544.
2016-08-04 14:29:01 INFO Traceback
RuntimeError: OrderedDict mutated during iteration
  File "/usr/lib/python3.5/site-packages/py3status/__init__.py", line 23, in main
    py3.setup()
  File "/usr/lib/python3.5/site-packages/py3status/core.py", line 276, in setup
    config = process_config(config_path, self)
  File "/usr/lib/python3.5/site-packages/py3status/parse_config.py", line 562, in process_config
    get_modules(config_info)
  File "/usr/lib/python3.5/site-packages/py3status/parse_config.py", line 558, in get_modules
    module = process_module(k, v, parent)
  File "/usr/lib/python3.5/site-packages/py3status/parse_config.py", line 544, in process_module
    for k, v in module.items():

2016-08-04 14:29:01 ERROR py3status: Setup error (RuntimeError) parse_config.py line 544. Please try to fix this and reload i3wm (Mod+Shift+R)
```

**Comment by tobes** [comment]
This config works for me.

It is odd that you see module.items() as `odict_items(...)` I see `ModuleDefinition(...)` but it is just a subclassed ordered dict. I'm running python 3.4.3 but I wouldn't think 3.5 would behave differently.

The config parser can be run standalone `python py3status/parse_config.py <path to config>` which might help with debugging.

Does changing line 544 to `for k, v in [x for x in module.items()]:` fix the issue?

**Comment by ikzk** [comment]
@tobes 
It gives the following result:

```
$ python3 parse_config.py ~/i3status.conf   

PARSING CONFIG FILE /home/alice/downloads/i3status.conf


Traceback (most recent call last):
  File "parse_config.py", line 642, in <module>
    pprint.pprint(process_config(file_name))
  File "parse_config.py", line 562, in process_config
    get_modules(config_info)
  File "parse_config.py", line 558, in get_modules
    module = process_module(k, v, parent)
  File "parse_config.py", line 544, in process_module
    for k, v in module.items():
RuntimeError: OrderedDict mutated during iteration
```

I'll give python 3.4 a try.

**Comment by tobes** [comment]
Did you try that possible fix?

**Comment by ikzk** [comment]
@tobes Oh, that's weird.. 3.4.3 also works on my computer, so the problem might be the inconsistence between python 3.5.2 and 3.4.3..........

**Comment by ikzk** [comment]
@tobes  https://github.com/ultrabug/py3status/pull/389 still gives 

```
PARSING CONFIG FILE /home/alice/downloads/i3status.conf


Traceback (most recent call last):
  File "parse_config.py", line 644, in <module>
    pprint.pprint(process_config(file_name))
  File "parse_config.py", line 562, in process_config
    get_modules(config_info)
  File "parse_config.py", line 558, in get_modules
    module = process_module(k, v, parent)
  File "parse_config.py", line 544, in process_module
    for k, v in module.items():
RuntimeError: OrderedDict mutated during iteration
```

**Comment by tobes** [comment]
Sorry I meant the [x for x in ...] Fix from my comment a few above. On my
phone so bit hard to type.

I'll try to install 3.5 over the weekend

**Comment by ikzk** [comment]
@tobes Yes changing line 544 to `for k, v in [x for x in module.items()]:` fixes the issue! Thanks for your help!

**Comment by tobes** [comment]
Cool I'll make a patch

**Comment by pydsigner** [comment]
@tobes please use just straight `list(module.items())` though, not a 
list comprehension.

**Comment by tobes** [comment]
@pydsigner sure thing

**Comment by tobes** [comment]
@ikzk if you can confirm that #391 fixes the issue that would be great.

Thanks for reporting these issues.  Hope you are enjoying py3status.

**Comment by ikzk** [comment]
@tobes Yes, it works perfectly. Thanks for your work!

**Comment by ultrabug** [comment]
Thanks for the report and nice debug guys !

**Comment by ultrabug** [comment]
It's merged now.
