### ISSUE TITLE
module_test cannot kill threads

### ISSUE THREAD

**Issue by ritze** [ultrabug/py3status#414]
When you testing a module with threads like the `mpris` module and try to abort the process than you get an error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "mpris.py", line 309, in _start_loop
    self._loop.run()
  File "/usr/lib/python3.5/site-packages/gi/overrides/GLib.py", line 576, in run
    raise KeyboardInterrupt
KeyboardInterrupt
```

After that error the process is still alive.

**Comment by tobes** [comment]
This is actually an issue in mpris.py rather than the module testing as such.

GObject.MainLoop is a fairly nasty thing imho the following patch fixes the issue
really `self._loop.quit()` should kill it but it does not appear to.

I think there is a better solution to this issue

```
diff --git a/py3status/modules/mpris.py b/py3status/modules/mpris.py
index 553e9ee..1e9bc65 100644
--- a/py3status/modules/mpris.py
+++ b/py3status/modules/mpris.py
@@ -97,6 +97,7 @@ Tested players:
 @author Moritz Lüdecke, tobes
 """
 
+import sys
 from datetime import timedelta
 from time import time
 from gi.repository import GObject
@@ -153,6 +154,7 @@ class Py3status:
 
     def __init__(self):
         self._dbus = None
+        self._kill = False
         self._mpris_players = {}
         self._mpris_names = {}
         self._mpris_name_index = {}
@@ -306,7 +308,11 @@ class Py3status:
 
     def _start_loop(self):
         self._loop = GObject.MainLoop()
-        self._loop.run()
+        GObject.timeout_add(1000, self._timeout)
+        try:
+            self._loop.run()
+        except KeyboardInterrupt:
+            self._kill = True
 
     def _name_owner_changed(self, *args):
         player_add = args[5][2]
@@ -441,6 +447,11 @@ class Py3status:
         t.daemon = True
         t.start()
 
+    def _timeout(self):
+        if self._kill:
+            self._loop.quit()
+            sys.exit(0)
+
     def _update_metadata(self, metadata=None):
         is_stream = False
 
@@ -529,6 +540,9 @@ class Py3status:
         if self._player and self._get_button_state(control_state):
             getattr(self._player, self._control_states[index]['action'])()
 
+    def kill(self):
+        self._kill = True
+
 if __name__ == "__main__":
     """
     Run module in test mode.
```

**Comment by ritze** [comment]
Seems legit.
