### ISSUE TITLE
Python 3.6 - TypeError: _catch() missing 1 required positional argument: 's'

### ISSUE THREAD

**Issue by MareinK** [ultrabug/py3status#649]
Hello, I've been using py3status on Arch Linux for a while now but recently I upgraded to Python 3.6 and it seems that has created a problem. When I run `py3status`, I get the following stacktrace.

```
Traceback (most recent call last):
  File "/usr/bin/py3status", line 11, in <module>
    load_entry_point('py3status==3.3', 'console_scripts', 'py3status')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/py3status/__init__.py", line 4, in <module>
    from py3status.core import Py3statusWrapper
  File "/usr/lib/python3.6/site-packages/py3status/core.py", line 22, in <module>
    from py3status.parse_config import process_config
  File "/usr/lib/python3.6/site-packages/py3status/parse_config.py", line 23, in <module>
    from py3status.private import PrivateHide, PrivateBase64
  File "/usr/lib/python3.6/site-packages/py3status/private.py", line 124, in <module>
    class PrivateBase64(Private):
TypeError: _catch() missing 1 required positional argument: 's'
```

This happens seemingly regardless of the contents of `.i3/i3status.conf'.

According to `pip show py3status`, I am running version 3.3 of py3status.

Any ideas what could be causing this? Something on my end, or a breaking change in Python 3.6?

Cheers!

**Comment by lasers** [comment]
I found something. Referencing you to issue https://github.com/ultrabug/py3status/issues/606.

**Comment by MareinK** [comment]
Should have searched more carefully, thanks!
