### ISSUE TITLE
battery_level.py module doesn't run under python3

### ISSUE THREAD

**Issue by thomas-** [ultrabug/py3status#67]
I get this error with python3 (works fine with python2)

```
Traceback (most recent call last):
  File "py3status/modules/battery_level.py", line 120, in <module>
    print(x.battery_level([], {}))
  File "py3status/modules/battery_level.py", line 50, in battery_level
    acpi_clean = acpi_raw.translate(None, ',')
TypeError: expected bytes, bytearray or buffer compatible object
```

**Comment by ultrabug** [comment]
Thanks a lot mate for the report and the fix !
