### ISSUE TITLE
nvidia_temp: not python 2 compatible 

### ISSUE THREAD

**Issue by tobes** [ultrabug/py3status#699]
``` 
lasers~/src/py3status/py3status/modules git:(master) python2 nvidia_temp.py
Traceback (most recent call last):
  File "nvidia_temp.py", line 79, in <module>
    module_test(Py3status)
  File "/home/chris/src/py3status/py3status/module_test.py", line 52, in module_test
    print(getattr(module, method)(*method_args))
  File "nvidia_temp.py", line 48, in nvidia_temp
    format_units=self.format_units
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 0: ordinal not in range(128)
```

**Comment by lasers** [comment]
I introduced helpers for nvidia_temp. Python2and3 tested OK. Pending review.

Adding format will break nvidia_temp. If we do this, I want to introduce bluetooth breakage too at same time. I will keep adding helpers everywhere.

**Comment by tobes** [comment]
>  I will keep adding helpers everywhere.

Cool, Do ones you can test in preference

**Comment by lasers** [comment]
Will do. That have been the case... Those I can't test, I'll mention "Untested."
