### ISSUE TITLE
TypeError in python 3.6

### ISSUE THREAD

**Issue by AlejandroCatalina** [ultrabug/py3status#716]
Hey there, awesome work here!

Nonetheless, after my last system update (arch Linux) python upgraded to 3.6 version. I'm guessing py3status is not fully compatible with it as for now because this error came up when my X system booted up:

```python
Traceback (most recent call last):
  File "/usr/bin/py3status", line 11, in <module>
    load_entry_point('py3status==3.1', 'console_scripts', 'py3status')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2642, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2296, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/alex/.local/lib/python3.6/site-packages/py3status/__init__.py", line 4, in <module>
    from py3status.core import Py3statusWrapper
  File "/home/alex/.local/lib/python3.6/site-packages/py3status/core.py", line 21, in <module>
    from py3status.parse_config import process_config
  File "/home/alex/.local/lib/python3.6/site-packages/py3status/parse_config.py", line 23, in <module>
    from py3status.private import PrivateHide, PrivateBase64
  File "/home/alex/.local/lib/python3.6/site-packages/py3status/private.py", line 124, in <module>
    class PrivateBase64(Private):
TypeError: _catch() missing 1 required positional argument: 's'
```

Anyone else is having this issue and can point me to a workable solution?

Thank you so much!

**Comment by tobes** [comment]
Hi,  Thanks for your report.

This is a known issue with python 3.6 that was first reported in #606 and fixed in PR #610.  This is included in py3status version 3.4 it should be available in aur packages `py3status` and `py3status-git` as well as version 3.4 or master from https://github.com/ultrabug/py3status

If this is not the case please reopen this issue
